# Catppuccin Mocha (Spiced Edition)
# https://catppuccin.com
# Vibe: Warm latte, cinnamon, and autumn. 


[colors]
background = #1e1e2eff
card_bg = #313244ff
card_selected = #45475aff
text_color = #ffffffff
subtext_color = #fab387ff
border_color = #eba0acff
bundle_bg = #313244cc
badge_bg = #eba0acff
badge_text_color = #ffffffff
workspace_color = #ffffffff