# Gruvbox Dark Theme
# https://github.com/morhetz/gruvbox

[colors]
background = #282828ff
card_bg = #3c3836ff
card_selected = #504945ff
text_color = #ebdbb2ff
subtext_color = #a89984ff
border_color = #fe8019ff
bundle_bg = #3c3836cc
badge_bg = #fe8019ff
badge_text_color = #282828ff
workspace_color = #ebdbb2ff
